/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-surface": "#191c1d",
        "tertiary": "#7a1d00",
        "tertiary-container": "#a32a01",
        "error-container": "#ffdad6",
        "link-gray": "#5C6673",
        "surface-bright": "#f8f9fa",
        "outline-variant": "#c4c5d7",
        "inverse-surface": "#2e3132",
        "on-secondary-fixed": "#191c1e",
        "on-error-container": "#93000a",
        "on-primary-fixed-variant": "#0039b3",
        "surface-container-highest": "#e1e3e4",
        "secondary": "#5c5f61",
        "primary": "#0033a2",
        "border-subtle": "#E6E8EB",
        "background": "#f8f9fa",
        "on-background": "#191c1d",
        "primary-fixed-dim": "#b6c4ff",
        "on-tertiary-container": "#ffbdab",
        "inverse-primary": "#b6c4ff",
        "surface-container": "#edeeef",
        "on-primary": "#ffffff",
        "on-secondary-container": "#626567",
        "on-tertiary": "#ffffff",
        "outline": "#747686",
        "tertiary-fixed": "#ffdbd1",
        "surface-container-high": "#e7e8e9",
        "secondary-fixed": "#e0e3e6",
        "on-secondary-fixed-variant": "#44474a",
        "tertiary-fixed-dim": "#ffb5a0",
        "inverse-on-surface": "#f0f1f2",
        "surface-container-low": "#f3f4f5",
        "secondary-container": "#e0e3e6",
        "surface-variant": "#e1e3e4",
        "on-tertiary-fixed": "#3b0900",
        "on-tertiary-fixed-variant": "#872100",
        "on-secondary": "#ffffff",
        "surface-tint": "#1950df",
        "surface-container-lowest": "#ffffff",
        "on-primary-container": "#bfcaff",
        "on-primary-fixed": "#001551",
        "primary-container": "#0247d7",
        "surface": "#f8f9fa",
        "on-error": "#ffffff",
        "on-surface-variant": "#434655",
        "primary-fixed": "#dce1ff",
        "surface-dim": "#d9dadb",
        "error": "#ba1a1a",
        "secondary-fixed-dim": "#c4c7ca",
        "text-main": "#111827",
        "neon-green": "#39ff14",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "container-max": "440px",
        "stack-lg": "2.5rem",
        "unit": "8px",
        "stack-sm": "0.5rem",
        "stack-md": "1.5rem",
        "margin-mobile": "1rem",
        "margin-desktop": "4rem",
        "gutter": "1.5rem"
      },
      fontFamily: {
        "apple": ["system-ui", "-apple-system", "sans-serif"],
        "label-md": ["system-ui", "-apple-system", "sans-serif"],
        "label-sm": ["system-ui", "-apple-system", "sans-serif"],
        "headline-lg": ["system-ui", "-apple-system", "sans-serif"],
        "body-md": ["system-ui", "-apple-system", "sans-serif"],
        "headline-md": ["system-ui", "-apple-system", "sans-serif"],
        "body-lg": ["system-ui", "-apple-system", "sans-serif"],
        "headline-lg-mobile": ["system-ui", "-apple-system", "sans-serif"],
        "display-xl-mobile": ["system-ui", "-apple-system", "sans-serif"],
        "label-caps": ["system-ui", "-apple-system", "sans-serif"]
      },
      fontSize: {
        "label-md": ["14px", { "lineHeight": "20px", "fontWeight": "500" }],
        "label-sm": ["12px", { "lineHeight": "16px", "letterSpacing": "0.01em", "fontWeight": "500" }],
        "label-caps": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "headline-lg": ["30px", { "lineHeight": "38px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "headline-md": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "32px", "fontWeight": "700" }],
        "display-xl-mobile": ["48px", { "lineHeight": "110%", "letterSpacing": "-0.02em", "fontWeight": "800" }],
        "display-xl": ["96px", { "lineHeight": "100%", "letterSpacing": "-0.04em", "fontWeight": "800" }]
      },
      maxWidth: {
        "container-max": "1440px"
      }
    },
  },
  plugins: [],
}
